### ISSUE TITLE
Add greenkeeper support

### ISSUE THREAD

**Issue by rajey** [mambopoint/mambopoint-mobile#3]
Greenkeeper help to ensure that all third party dependencies used in the application are up to date and they are not breaking builds

**Comment by chingaloEric** [comment]
![git](https://user-images.githubusercontent.com/36584802/56119623-2b132c80-5f75-11e9-8c31-07b58e821458.png)
I have created with greenkeeper an account already but my request to access source code in mambopoint organisation is pending. So I'm failing to enable it in our mobile source code. @rajey

**Comment by rajey** [comment]
I have added you as admin
