### ISSUE TITLE
Add application description in the README file

### ISSUE THREAD

**Issue by rajey** [mambopoint/mambopoint-mobile#6]
We need to update README file with general information describing the purpose of this application

**Comment by mmahundi** [comment]
Yes. We will have to do that. Is this intended for developers?

**Comment by mmahundi** [comment]
I am familiarising with github to see how I can add contents to README. I will get it started

**Comment by rajey** [comment]
Usually description builds a good concept of what this is, not necessarily intended for developer but even one involved.
